### create grave post
POST http://localhost:8080/api/graves
Content-Type: application/json

{
  "name": "N",
  "row": 12,
  "column": 2
}

### create grave with the same implementation to proof that it will not saved into the database
POST http://localhost:8080/api/graves
Content-Type: application/json

{
  "name": "N",
  "row": 12,
  "column": 2
}

### find grave by id
GET http://localhost:8080/api/graves/1
Accept: application/json

### select graves in a parcel with the given name
GET http://localhost:8080/api/graves/parcel?name=N
Accept: application/json

### select graves in a parcel with the given name and in the given row
GET http://localhost:8080/api/graves/parcel?name=N&row=12
Accept: application/json
